name: Copy to One Repo
# wanted/duplicate/reply/close

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
    secrets:
      PERSONAL_TOKEN:
        required: true

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.github/workflows
        src_branch: main
        dst_path: /.github/
        dst_branch: develop
        dst_owner: Tencent
        dst_repo_name: ${{ inputs.repo }}
        filter: '**/*.temp.yml'
        username: 94dreamer
        email: 503633021@qq.com
        commit_message: 'ci: update files "/.github/workflows" from "Tencent/tdesign"'